#!/usr/bin/env python3
import argparse
import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
sys.path.insert(0, str(SCRIPT_DIR / "lib"))

from discord_modules import discover_modules, validate_module_manifests  # noqa: E402


COMMON_INPUTS = {
    "project_name": "var.project_name",
    "zip_root": "local.zip_root",
    "lambda_runtime": "var.lambda_runtime",
    "lambda_architecture": "var.lambda_architecture",
    "router_lambda_memory_size": "var.router_lambda_memory_size",
    "router_lambda_timeout": "var.router_lambda_timeout",
    "worker_lambda_memory_size": "var.worker_lambda_memory_size",
    "worker_lambda_timeout": "var.worker_lambda_timeout",
    "tags": "local.common_tags",
}


def terraform_id(name: str) -> str:
    value = re.sub(r"[^0-9A-Za-z_]", "_", name)
    if not value or value[0].isdigit():
        value = f"module_{value}"
    return value


def variable_blocks(path: Path):
    if not path.exists():
        return {}

    lines = path.read_text(encoding="utf-8").splitlines()
    blocks = {}
    i = 0
    while i < len(lines):
        match = re.match(r'\s*variable\s+"([^"]+)"\s*\{', lines[i])
        if not match:
            i += 1
            continue

        name = match.group(1)
        start = i
        depth = 0
        while i < len(lines):
            depth += lines[i].count("{")
            depth -= lines[i].count("}")
            i += 1
            if depth == 0:
                break
        blocks[name] = "\n".join(lines[start:i])
    return blocks


def output_names(path: Path):
    if not path.exists():
        return []
    text = path.read_text(encoding="utf-8")
    return re.findall(r'(?m)^\s*output\s+"([^"]+)"\s*\{', text)


def generated_header():
    return "\n".join(
        [
            "# This file is generated by scripts/generate-terraform-modules.py.",
            "# Do not edit by hand; update module manifests or module Terraform instead.",
            "",
        ]
    )


def generate(repo_root: Path):
    validate_module_manifests(repo_root)
    modules = [
        module
        for module in discover_modules(repo_root)
        if isinstance(module["manifest"].get("terraform"), str)
        and module["manifest"].get("terraform")
    ]

    root_variables = variable_blocks(repo_root / "infra" / "terraform" / "variables.tf")
    generated_variables = {}
    generated_module_blocks = []
    generated_outputs = []
    lambda_name_outputs = []

    manifest_paths = [
        f'    jsondecode(file("${{path.module}}/../../{module["manifest_path"].relative_to(repo_root)}"))'
        for module in modules
    ]

    locals_body = ["locals {", "  module_manifests = ["]
    if manifest_paths:
        locals_body.extend(f"{path}," for path in manifest_paths)
    locals_body.extend(["  ]", "}"])

    for module in modules:
        manifest = module["manifest"]
        module_name = manifest["name"]
        module_id = terraform_id(module_name)
        terraform_dir = module["dir"] / manifest["terraform"]
        module_vars = variable_blocks(terraform_dir / "variables.tf")

        inputs = []
        for var_name in sorted(module_vars):
            if var_name in COMMON_INPUTS:
                inputs.append((var_name, COMMON_INPUTS[var_name]))
                continue

            if var_name in root_variables or var_name in generated_variables:
                inputs.append((var_name, f"var.{var_name}"))
                continue

            generated_variables[var_name] = module_vars[var_name]
            inputs.append((var_name, f"var.{var_name}"))

        block = [
            f'module "{module_id}" {{',
            f'  source = "../../{terraform_dir.relative_to(repo_root)}"',
            "",
        ]
        max_name_len = max((len(name) for name, _ in inputs), default=0)
        for name, value in inputs:
            block.append(f"  {name.ljust(max_name_len)} = {value}")
        block.append("}")
        generated_module_blocks.append("\n".join(block))

        outputs = output_names(terraform_dir / "outputs.tf")
        if "lambda_names" in outputs:
            lambda_name_outputs.append(f"module.{module_id}.lambda_names")
        for output in outputs:
            if output == "lambda_names":
                continue
            generated_outputs.extend(
                [
                    f'output "module_{module_id}_{output}" {{',
                    f'  description = "Output {output} from module {module_name}."',
                    f"  value       = module.{module_id}.{output}",
                    "}",
                    "",
                ]
            )

    if lambda_name_outputs:
        lambda_value = f"sort(concat({', '.join(lambda_name_outputs)}))"
    else:
        lambda_value = "[]"
    generated_outputs = [
        'output "worker_lambda_names" {',
        '  description = "Names of downstream worker Lambda functions from installed modules."',
        f"  value       = {lambda_value}",
        "}",
        "",
        *generated_outputs,
    ]

    variables_text = generated_header()
    if generated_variables:
        variables_text += "\n\n".join(generated_variables[name] for name in sorted(generated_variables))
        variables_text += "\n"

    modules_text = generated_header()
    modules_text += "\n".join(locals_body)
    if generated_module_blocks:
        modules_text += "\n\n" + "\n\n".join(generated_module_blocks)
    modules_text += "\n"

    outputs_text = generated_header() + "\n".join(generated_outputs)

    return {
        repo_root / "infra" / "terraform" / "generated_module_variables.tf": variables_text,
        repo_root / "infra" / "terraform" / "generated_modules.tf": modules_text,
        repo_root / "infra" / "terraform" / "generated_module_outputs.tf": outputs_text,
    }


def main():
    parser = argparse.ArgumentParser(
        description="Generate root Terraform module wiring from modules/*/module.manifest.json."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if generated Terraform files are out of date.",
    )
    args = parser.parse_args()

    files = generate(REPO_ROOT)
    changed = []
    for path, content in files.items():
        if path.exists() and path.read_text(encoding="utf-8") == content:
            continue
        changed.append(path)
        if not args.check:
            path.write_text(content, encoding="utf-8")

    if args.check and changed:
        for path in changed:
            print(f"out of date: {path.relative_to(REPO_ROOT)}", file=sys.stderr)
        return 1

    if changed:
        for path in changed:
            print(f"generated {path.relative_to(REPO_ROOT)}")
    else:
        print("Terraform module wiring is up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
